/**
 * Curated Google Places search terms for iconic city hero photos.
 * Falls back to a generic landmark query when not in this map.
 */
export const CITY_HERO_QUERIES: Record<string, string> = {
  // Asia
  "tokyo":             "Shibuya Crossing Tokyo",
  "kyoto":             "Fushimi Inari Kyoto",
  "osaka":             "Dotonbori Osaka",
  "seoul":             "Gyeongbokgung Palace Seoul",
  "bangkok":           "Wat Arun Bangkok",
  "chiang-mai":        "Chiang Mai temples",
  "singapore":         "Marina Bay Sands Singapore",
  "kuala-lumpur":      "Petronas Towers Kuala Lumpur",
  "hong-kong":         "Hong Kong skyline Victoria Harbour",
  "shanghai":          "Shanghai skyline Pudong",
  "beijing":           "Forbidden City Beijing",
  "ho-chi-minh-city":  "Ho Chi Minh City skyline",
  "ha-long":           "Halong Bay Vietnam",
  "hanoi":             "Hanoi old quarter",
  "bali":              "Tegallalang rice terraces Bali",
  "ubud":              "Ubud rice terraces",
  "kuta":              "Kuta beach Bali",
  "phuket":            "Phuket beach Thailand",
  "siem-reap":         "Angkor Wat Siem Reap",
  "tel-aviv":          "Tel Aviv beach skyline",
  "dubai":             "Burj Khalifa Dubai",
  "mumbai":            "Gateway of India Mumbai",
  "jaipur":            "Hawa Mahal Jaipur",
  // Europe
  "paris":             "Eiffel Tower Paris",
  "london":            "Tower Bridge London",
  "rome":              "Colosseum Rome",
  "venice":            "Grand Canal Venice gondola",
  "florence":          "Florence Duomo skyline",
  "milan":             "Milan Duomo",
  "barcelona":         "Sagrada Familia Barcelona",
  "madrid":            "Plaza Mayor Madrid",
  "marbella":          "Marbella beach old town",
  "seville":           "Plaza de España Seville",
  "amsterdam":         "Amsterdam canals",
  "berlin":            "Brandenburg Gate Berlin",
  "munich":            "Marienplatz Munich",
  "vienna":            "Schönbrunn Palace Vienna",
  "prague":            "Charles Bridge Prague",
  "budapest":          "Parliament Building Budapest Danube",
  "lisbon":            "Lisbon tram Alfama",
  "porto":             "Porto Ribeira Douro river",
  "athens":            "Acropolis Athens",
  "santorini":         "Oia Santorini blue domes",
  "mykonos":           "Mykonos windmills",
  "istanbul":          "Hagia Sophia Istanbul",
  "dublin":            "Trinity College Dublin",
  "edinburgh":         "Edinburgh Castle",
  "reykjavik":         "Reykjavik Hallgrimskirkja",
  "reine":             "Reine Lofoten red rorbuer",
  "stockholm":         "Stockholm Gamla Stan",
  "copenhagen":        "Nyhavn Copenhagen",
  "oslo":              "Oslo Opera House",
  "zurich":            "Zurich Limmat river",
  // North America
  "new-york":          "Manhattan skyline Brooklyn Bridge",
  "los-angeles":       "Los Angeles Hollywood sign",
  "san-francisco":     "Golden Gate Bridge San Francisco",
  "chicago":           "Chicago skyline lakefront",
  "miami":             "Miami South Beach Art Deco",
  "las-vegas":         "Las Vegas Strip neon",
  "washington":        "Washington Monument Cherry Blossoms",
  "boston":            "Boston Acorn Street Beacon Hill",
  "seattle":           "Space Needle Seattle Mount Rainier",
  "honolulu":          "Waikiki Diamond Head Honolulu",
  "vancouver":         "Vancouver Stanley Park skyline",
  "toronto":           "Toronto CN Tower skyline",
  "mexico-city":       "Mexico City Zocalo cathedral",
  "tulum":             "Tulum beach Mayan ruins",
  "cabo-san-lucas":    "Cabo San Lucas El Arco",
  "cancun":            "Cancun beach turquoise",
  "springdale-ut":     "Zion National Park red cliffs",
  "moab":              "Arches National Park Delicate Arch",
  "estes-park":        "Rocky Mountain National Park",
  "jackson":           "Grand Tetons Jackson Hole",
  "west-yellowstone":  "Grand Prismatic Spring Yellowstone",
  // South America
  "rio-de-janeiro":    "Christ Redeemer Rio Sugarloaf",
  "buenos-aires":      "Buenos Aires La Boca colorful",
  "cusco":             "Machu Picchu Cusco",
  "lima":              "Lima Miraflores cliffs",
  "cartagena":         "Cartagena old town colorful",
  // Africa
  "cape-town":         "Cape Town Table Mountain",
  "marrakech":         "Marrakech Jemaa el-Fnaa",
  "cairo":             "Pyramids Giza Cairo",
  "luxor":             "Karnak Temple Luxor",
  // Oceania
  "sydney":            "Sydney Opera House Harbour Bridge",
  "melbourne":         "Melbourne laneways skyline",
  "auckland":          "Auckland Sky Tower harbour",
  "queenstown":        "Queenstown Lake Wakatipu",
};

export function getHeroQuery(citySlug: string, cityName: string, countryName: string): string {
  if (CITY_HERO_QUERIES[citySlug]) return CITY_HERO_QUERIES[citySlug];
  return `${cityName} ${countryName} landmark`;
}
