export const COUNTRY_FLAGS: Record<string, string> = {
  "Japan": "🇯🇵",
  "Thailand": "🇹🇭",
  "South Korea": "🇰🇷",
  "Korea": "🇰🇷",
  "China": "🇨🇳",
  "Indonesia": "🇮🇩",
  "Vietnam": "🇻🇳",
  "Cambodia": "🇰🇭",
  "Singapore": "🇸🇬",
  "Malaysia": "🇲🇾",
  "Philippines": "🇵🇭",
  "Sri Lanka": "🇱🇰",
  "India": "🇮🇳",
  "Nepal": "🇳🇵",
  "Maldives": "🇲🇻",
  "Australia": "🇦🇺",
  "New Zealand": "🇳🇿",
  "France": "🇫🇷",
  "Italy": "🇮🇹",
  "Spain": "🇪🇸",
  "Portugal": "🇵🇹",
  "Germany": "🇩🇪",
  "United Kingdom": "🇬🇧",
  "UK": "🇬🇧",
  "Netherlands": "🇳🇱",
  "Switzerland": "🇨🇭",
  "Austria": "🇦🇹",
  "Greece": "🇬🇷",
  "Croatia": "🇭🇷",
  "Czech Republic": "🇨🇿",
  "Poland": "🇵🇱",
  "Hungary": "🇭🇺",
  "Sweden": "🇸🇪",
  "Norway": "🇳🇴",
  "Denmark": "🇩🇰",
  "Iceland": "🇮🇸",
  "Ireland": "🇮🇪",
  "Belgium": "🇧🇪",
  "Turkey": "🇹🇷",
  "Morocco": "🇲🇦",
  "Egypt": "🇪🇬",
  "South Africa": "🇿🇦",
  "Kenya": "🇰🇪",
  "Tanzania": "🇹🇿",
  "UAE": "🇦🇪",
  "United Arab Emirates": "🇦🇪",
  "Qatar": "🇶🇦",
  "Israel": "🇮🇱",
  "Jordan": "🇯🇴",
  "United States": "🇺🇸",
  "USA": "🇺🇸",
  "Canada": "🇨🇦",
  "Mexico": "🇲🇽",
  "Brazil": "🇧🇷",
  "Argentina": "🇦🇷",
  "Peru": "🇵🇪",
  "Colombia": "🇨🇴",
  "Chile": "🇨🇱",
  "Costa Rica": "🇨🇷",
  "Cuba": "🇨🇺",
};

export function getCountryFlag(country: string): string {
  return COUNTRY_FLAGS[country] ?? "🌍";
}
